### ISSUE TITLE
create a service definition in proto?

### ISSUE THREAD

**Issue by jamescarr** [ha/doozerd#15]
Maybe this is just my newbishness to protocol buffers, but I'm completely lost. 

Maybe it would help if the proto definition defined a service that one could then intiialize and call? Because right now I can't seem to do jack with doozerd and protocol buffers by hand. I tried building a request and sending it over a tcp socket to localhost on port 8043 but running dozer from the commandline for the path gives me nothing.

**Comment by bmizerany** [comment]
Do you mind showing us the steps/code you used to produce this problem?

Closing for now. We can reopen this issue once we have more information to work with.
