### ISSUE TITLE
doozerd leaks memory?

### ISSUE THREAD

**Issue by tv42** [ha/doozerd#2]
I left doozerd running for less than two days, and it ended up consuming surprising amounts of RAM:

```
$ date
Sat Apr 23 11:17:45 PDT 2011
$ ps uww 27644
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
tv       27644  0.7 10.5 454924 400816 pts/172 Sl+  Apr21  17:01 doozerd
```

The sequence numbers had reached ~80k, but there was nothing else interesting in the logs:

```
DOOZER 2011/04/23 11:17:55.065502 learn seqn=79952
```

For comparison, here's doozerd at seqn=100, which seems like an adequate warmup (though it probably won't read max size before gc):

``
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
tv       19181  1.4  0.1  42252  4220 pts/172  Sl   11:24   0:00 doozerd

```

This is on an amd64 ubuntu 10.10 machine, with 6g from go.git f1f3e6292aecd165692c41cd2dd2f5886b5958eb (2011-04-15).

I don't know yet if this is an issue with Go's garbage collection, but given how nice (really nice!) and simple doozerd is, I didn't expect the 10x growth, and no other Go app has made me really wonder about the size.
```

**Comment by bmizerany** [comment]
Interesting.  I'm sorry to get back to you so late.  Have you seen this with Doozer 0.6 too?

**Comment by bmizerany** [comment]
Please try again with 0.7 and see also:
https://groups.google.com/forum/#!topic/doozer/5MOBldK3OHI
