### ISSUE TITLE
Cannot run on Mac OS X 10.7

### ISSUE THREAD

**Issue by oinopion** [ha/doozerd#33]
I've downloaded this binary:
https://github.com/downloads/ha/doozerd/doozerd-0.8-darwin-amd64.tar.gz
Unpacked, chmodded and tried to run. Getting following error:

```
./doozerd
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
[1]    21635 abort      ./doozerd
```

**Comment by twopoint718** [comment]
I am seeing the same thing:

```
$ ./doozerd
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
Abort trap: 6
```

**Comment by fd** [comment]
the same here

**Comment by roblight** [comment]
ditto

**Comment by newobj** [comment]
Same here. And trying to compile I get the following too:

BRIANs-iMac:doozerd newobj$ ./all.sh 

# github.com/ha/doozer

/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:184: cannot use &t.req (type *request) as type proto.Message in function argument:
    *request does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:198: cannot use &r (type *response) as type proto.Message in function argument:
    *response does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:294: undefined: proto.GetInt64
/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:326: undefined: proto.GetInt64
/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt32
/usr/local/go/src/pkg/github.com/ha/doozer/conn.go:412: undefined: proto.GetInt64
/usr/local/go/src/pkg/github.com/ha/doozer/err.go:33: cannot call non-function proto.GetString (type struct {})
/usr/local/go/src/pkg/github.com/ha/doozer/msg.pb.go:127: cannot use this (type *request) as type proto.Message in function argument:
    *request does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozer/msg.pb.go:142: cannot use this (type *response) as type proto.Message in function argument:
    *response does not implement proto.Message (missing ProtoMessage method)

# github.com/ha/doozerd/consensus

/usr/local/go/src/pkg/github.com/ha/doozerd/consensus/m.pb.go:65: cannot use this (type *msg) as type proto.Message in function argument:
    *msg does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozerd/consensus/manager.go:230: cannot use &m (type *msg) as type proto.Message in function argument:
    *msg does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozerd/consensus/manager.go:240: cannot use &p.msg (type *msg) as type proto.Message in function argument:
    *msg does not implement proto.Message (missing ProtoMessage method)
/usr/local/go/src/pkg/github.com/ha/doozerd/consensus/run.go:65: cannot use m (type *msg) as type proto.Message in function argument:
    *msg does not implement proto.Message (missing ProtoMessage method)

So, no doozerd love for me :(

**Comment by cvillecsteele** [comment]
Same problem here.

**Comment by Lazarus404** [comment]
And me, compiling on Windows under Cygwin.  Getting:

# github.com/ha/doozerd/consensus

G:\Go\src\pkg\github.com\ha\doozerd\consensus\m.pb.go:65: cannot use this (type *msg) as type proto.Message in function argument:
        *msg does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozerd\consensus\manager.go:230: cannot use &m (type *msg) as type proto.Message in function argument:
        *msg does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozerd\consensus\manager.go:240: cannot use &p.msg (type *msg) as type proto.Message in function argument:
        *msg does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozerd\consensus\run.go:65: cannot use m (type *msg) as type proto.Message in function argument:
        *msg does not implement proto.Message (missing ProtoMessage method)

# github.com/ha/doozer

G:\Go\src\pkg\github.com\ha\doozer\conn.go:184: cannot use &t.req (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozer\conn.go:198: cannot use &r (type *response) as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozer\conn.go:294: undefined: proto.GetInt64
G:\Go\src\pkg\github.com\ha\doozer\conn.go:326: undefined: proto.GetInt64
G:\Go\src\pkg\github.com\ha\doozer\conn.go:412: undefined: proto.GetInt32
G:\Go\src\pkg\github.com\ha\doozer\conn.go:412: undefined: proto.GetInt64
G:\Go\src\pkg\github.com\ha\doozer\err.go:33: cannot call non-function proto.GetString (type struct {})
G:\Go\src\pkg\github.com\ha\doozer\msg.pb.go:127: cannot use this (type *request) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
G:\Go\src\pkg\github.com\ha\doozer\msg.pb.go:142: cannot use this (type *response) as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)

**Comment by alex-ethier** [comment]
same here....

```
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
Abort trap: 6
```

**Comment by bketelsen** [comment]
This will be fixed in an upcoming pull request.

**Comment by dropwhile** [comment]
<3

**Comment by sourcec0de** [comment]
Was this ever resolved? Is there a reference to the commit that fixes this issue?

**Comment by alexanderbartels** [comment]
same here... (Version 0.7 and Version 0.8)

libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
Abort trap: 6

solution at https://github.com/ha/doozerd/issues/62 worked for me.
-> use got get to install doozerd
