### ISSUE TITLE
Can't compile - missing pretty.go

### ISSUE THREAD

**Issue by gar1t** [ha/doozerd#35]
I get this error when running make.sh:

```
package github.com/ha/doozer
    imports code.google.com/p/goprotobuf/proto
    imports github.com/kr/pretty.go
    imports github.com/kr/pretty.go
    imports github.com/kr/pretty.go: no Go source files in .go/src/github.com/kr/pretty.go
```

**Comment by blakesmith** [comment]
Same here. It looks like it's accidentally pulling in [pretty.go](https://github.com/kr/pretty.go) which is the old repository location. I tried to point `conn_test.go` to the [new repo](https://github.com/kr/pretty), but with no luck. Anyone else have a fix?

**Comment by blakesmith** [comment]
It looks like it traces back to: https://github.com/ha/doozer/pull/16. Since doozerd has a dependency on the doozer client (to mostly run tests it seems), this fix needs to get pulled in for doozerd to build.

**Comment by bketelsen** [comment]
Build fix coming shortly, closing.
