### ISSUE TITLE
make 4ad/doozerd the primary repository

### ISSUE THREAD

**Issue by jmhodges** [ha/doozerd#36]
Currently, 4ad/doozerd compiles against go1 and is more actively maintained. A support ticket to Github made by @ha could "flip" the fork status of the ha/doozerd and 4ad/doozerd.

Similarly, with ha/doozer and 4ad/doozer, I believe.

This would make it more clear to new users which repo is more available (and might help clear up the strong google juice ha/doozerd has over 4ad's).

**Comment by abh** [comment]
looks like the 4ad repository is dormant, too.  :confused:

**Comment by dgryski** [comment]
This can probably be closed now that the community is converging on this repository.

**Comment by bketelsen** [comment]
Agreed   Closed.

**Comment by bketelsen** [comment]
https://groups.google.com/forum/m/?fromgroups#!topic/doozer/oUuhBwQ_Ga4

History
