### ISSUE TITLE
Configuration Management

### ISSUE THREAD

**Issue by bketelsen** [ha/doozerd#43]
Configuration management needs to be improved.   Placeholder issue.  Specifics should be added as separate GH issues.

**Comment by mreiferson** [comment]
@bketelsen what sort of things did you have in mind here separate from what we started to work on in #34 (and now #46)?

**Comment by bketelsen** [comment]
I'm not sure - it was a note from our video meeting.  I suspect completing #34 and #46 will solve everyone's immediate needs.

**Comment by mreiferson** [comment]
closing in favor of #46 (anyone feel free to open any other specific issues they would like)
