### ISSUE TITLE
0.8 (everything) and current master (web view) not working on Mac OS 10.8

### ISSUE THREAD

**Issue by gregkare** [ha/doozerd#62]
When compiling from today's master, I get the same issue originally reported as #32: the web view doesn't work (can't connect). When using the 0.8 packages in [downloads](https://github.com/ha/doozerd/downloads), both 32 and 64 bit binaries give the same result on my machine:

```
$ doozerd
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
Abort trap: 6
```

Almost the same result as root:

```
$ sudo doozerd
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
```

And it's the same trying to use the help command:

```
$ doozerd --help
libcgo: thread-local storage 0x108 not at %gs:0x8a0 - x=0 y=0
Abort trap: 6
```

Do you need more information?

**Comment by mreiferson** [comment]
cannot reproduce with current master... can you show the command line you're using?

**Comment by grk** [comment]
@gkarekinian Had the same issue, it works fine when I install with 'go get github.com/ha/doozerd'. I guess you could try that.
